// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as CamlinternalOO from "bs-platform/lib\\es6/camlinternalOO.js";

var shared = [
  "listen",
  "get"
];

var mock_user = {
  id: "id",
  name: "name",
  imageUrl: "url",
  email: "email"
};

var $$class = CamlinternalOO.create_table(["getBasicProfile"]);

var getBasicProfile = CamlinternalOO.get_method_label($$class, "getBasicProfile");

CamlinternalOO.set_method($$class, getBasicProfile, (function (_, _$1) {
        return mock_user;
      }));

CamlinternalOO.init_class($$class);

var mock_google_user = CamlinternalOO.create_object_opt(0, $$class);

var $$class$1 = CamlinternalOO.create_table(shared);

var ids = CamlinternalOO.get_method_labels($$class$1, shared);

var listen = ids[0];

var get = ids[1];

CamlinternalOO.set_methods($$class$1, /* array */[
      get,
      (function (_, _$1) {
          return mock_google_user;
        }),
      listen,
      (function (_, _$1) {
          return /* () */0;
        })
    ]);

CamlinternalOO.init_class($$class$1);

var mock_current_user = CamlinternalOO.create_object_opt(0, $$class$1);

var mock_auth_instance = {
  currentUser: mock_current_user
};

describe("Expect", (function () {
        return Jest.test("toBe", (function () {
                      return Jest.Expect[/* toBe */2](mock_user, Jest.Expect[/* expect */0](mock_user));
                    }));
      }));

export {
  mock_user ,
  mock_google_user ,
  mock_current_user ,
  mock_auth_instance ,
  
}
/* class Not a pure module */
