// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as GoogleData  from "./GoogleData";

function make(children) {
  return ReasonReact.wrapJsForReason(GoogleData, { }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
