// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Curry          from "bs-platform/lib/es6/curry.js";
import * as $$String       from "bs-platform/lib/es6/string.js";
import * as Js_dict        from "bs-platform/lib/es6/js_dict.js";
import * as Process        from "process";
import * as CamlinternalOO from "bs-platform/lib/es6/camlinternalOO.js";

function fileToJs(param) {
  return {
          id: param[/* id */0],
          name: param[/* name */1],
          selected: param[/* selected */2],
          icon_link: param[/* icon_link */3],
          mimeType: param[/* mimeType */4]
        };
}

function fileFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* name */param.name,
          /* selected */param.selected,
          /* icon_link */param.icon_link,
          /* mimeType */param.mimeType
        ];
}

var read_scope = "https://www.googleapis.com/auth/drive.readonly";

var gapi_loaded = [/* false */0];

function get_instance(callback) {
  if (gapi_loaded[0]) {
    return Curry._1(callback, /* Instance */0);
  } else {
    var cb = function () {
      gapi_loaded[0] = /* true */1;
      return Curry._1(callback, /* Instance */0);
    };
    gapi.load("client:auth2", cb);
    return /* () */0;
  }
}

function do_things() {
  return gapi.client.init({
              apiKey: Process.env["REACT_APP_API_KEY"],
              clientId: Process.env["REACT_APP_CLIENT_ID"],
              scope: read_scope
            });
}

var class_tables = [
  0,
  0,
  0
];

function login() {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], 0);
}

var class_tables$1 = [
  0,
  0,
  0
];

function get_files_in_folder() {
  if (!class_tables$1[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables$1[0] = env_init;
  }
  return Curry._1(class_tables$1[0], 0);
}

var class_tables$2 = [
  0,
  0,
  0
];

function get_recent_files() {
  if (!class_tables$2[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables$2[0] = env_init;
  }
  return Curry._1(class_tables$2[0], 0);
}

function get_files(_, _$1, _$2, _$3) {
  Js_dict.fromList(/* :: */[
        /* tuple */[
          "corpora",
          "user"
        ],
        /* :: */[
          /* tuple */[
            "fields",
            "files(" + ($$String.concat(",", /* :: */[
                    "id",
                    /* :: */[
                      "name",
                      /* :: */[
                        "mimeType",
                        /* :: */[
                          "modifiedTime",
                          /* :: */[
                            "iconLink",
                            /* :: */[
                              "webViewLink",
                              /* :: */[
                                "webContentLink",
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]) + "), nextPageToken")
          ],
          /* [] */0
        ]
      ]);
  return /* () */0;
}

var write_scope = "https://www.googleapis.com/auth/drive";

export {
  fileToJs            ,
  fileFromJs          ,
  read_scope          ,
  write_scope         ,
  gapi_loaded         ,
  get_instance        ,
  do_things           ,
  login               ,
  get_files_in_folder ,
  get_recent_files    ,
  get_files           ,
  
}
/* Js_dict Not a pure module */
