// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as React           from "react";
import * as ReasonReact     from "reason-react/src/ReasonReact.js";
import * as Utils$EasyDrive from "../../Utils.bs.js";

(( require('./FileItem.css') ));

var file_icon = ( require('../../images/icons/file.png') );

var component = ReasonReact.statelessComponent("FileItem");

function make(name, selected, $staropt$star, _) {
  var icon_link = $staropt$star ? $staropt$star[0] : file_icon;
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var selectedClass = selected !== 0 ? "selected-file" : "";
      return React.createElement("div", {
                  className: "file-item flex items-center" + selectedClass
                }, React.createElement("img", {
                      className: "file-logo",
                      alt: "File logo",
                      height: "30px",
                      src: icon_link,
                      width: "30px"
                    }), React.createElement("span", {
                      className: "file-item-name flex-auto ellipsis"
                    }, Utils$EasyDrive.stringElem(name)));
    });
  return newrecord;
}

export {
  file_icon ,
  component ,
  make      ,
  
}
/*  Not a pure module */
