// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ReasonReact        from "reason-react/src/ReasonReact.js";
import * as Pdf$EasyDrive      from "./Pdf.bs.js";
import * as Image$EasyDrive    from "./Image.bs.js";
import * as Utils$EasyDrive    from "../../Utils.bs.js";
import * as Markdown$EasyDrive from "./Markdown.bs.js";

(( require('./Preview.css') ));

var component = ReasonReact.statelessComponent("Preview");

function make(name, mimeType, webContentLink, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var url = webContentLink ? "export=view".replace(webContentLink[0], "export=download") : "";
      switch (mimeType) {
        case "application/pdf" : 
            return ReasonReact.element(/* None */0, /* None */0, Pdf$EasyDrive.make(url, /* array */[]));
        case "image/jpeg" : 
            return ReasonReact.element(/* None */0, /* None */0, Image$EasyDrive.make(url, name, /* array */[]));
        case "text/x-markdown" : 
            return ReasonReact.element(/* None */0, /* None */0, Markdown$EasyDrive.make("Markdown content placeholder", /* array */[]));
        default:
          return Utils$EasyDrive.stringElem("Preview");
      }
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.name, jsProps.mimeType, jsProps.webContentLink, /* array */[]);
      }));

export {
  component ,
  make      ,
  $$default ,
  $$default   as default,
  
}
/*  Not a pure module */
