// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as React              from "react";
import * as ReasonReact        from "reason-react/src/ReasonReact.js";
import * as Pdf$EasyDrive      from "./Pdf.bs.js";
import * as Image$EasyDrive    from "./Image.bs.js";
import * as Utils$EasyDrive    from "../../Utils.bs.js";
import * as Markdown$EasyDrive from "./Markdown.bs.js";

(( require('./Preview.css') ));

var component = ReasonReact.statelessComponent("Preview");

function make(name, mimeType, webContentLink, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var url = webContentLink ? "export=view".replace(webContentLink[0], "export=download") : "";
      switch (mimeType) {
        case "application/pdf" : 
            return ReasonReact.element(/* None */0, /* None */0, Pdf$EasyDrive.make(url, /* array */[]));
        case "image/jpeg" : 
            return ReasonReact.element(/* None */0, /* None */0, Image$EasyDrive.make(url, name, /* array */[]));
        case "text/x-markdown" : 
            return ReasonReact.element(/* None */0, /* None */0, Markdown$EasyDrive.make("Markdown content placeholder", /* array */[]));
        default:
          return Utils$EasyDrive.stringElem("Preview");
      }
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.name, jsProps.mimeType, jsProps.webContentLink, /* array */[]);
      }));

var component$1 = ReasonReact.statelessComponent("Pdf");

function make$1(uri, _) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, Utils$EasyDrive.stringElem("PDF" + uri));
    });
  return newrecord;
}

var $$default$1 = ReasonReact.wrapReasonForJs(component$1, (function (jsProps) {
        return make$1(jsProps.uri, /* array */[]);
      }));

var Pdf = /* module */[
  /* component */component$1,
  /* make */make$1,
  /* default */$$default$1
];

export {
  component ,
  make      ,
  $$default ,
  $$default   as default,
  Pdf       ,
  
}
/*  Not a pure module */
