// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as GoogleData from "./GoogleData";

function make(children) {
  return ReasonReact.wrapJsForReason(GoogleData.default, { }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
