// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

(( require('./Image.css') ));

var component = ReasonReact.statelessComponent("Image");

function make(src, alt, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "preview-image"
                }, React.createElement("img", {
                      alt: alt,
                      src: src
                    }));
    });
  return newrecord;
}

export {
  component ,
  make ,
  
}
/*  Not a pure module */
