// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as LocalCache from "./LocalCache";

function make(cache_key, get_files, children) {
  return ReasonReact.wrapJsForReason(LocalCache, {
              cacheKey: cache_key,
              getFiles: get_files
            }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
