// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Utils$ReactTemplate from "../Utils.bs.js";

var component = ReasonReact.statelessComponent("Pdf");

function make(uri, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, Utils$ReactTemplate.stringElem("PDF" + uri));
    });
  return newrecord;
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
