// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Pdf$Drive from "./Pdf.bs.js";
import * as Image$Drive from "./Image.bs.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Utils$Drive from "../Utils.bs.js";
import * as Markdown$Drive from "./Markdown.bs.js";

(( require('./Preview.css') ));

var component = ReasonReact.statelessComponent("Preview");

function make(file, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var webContentLink = file[/* webContentLink */4];
      var url = (webContentLink == null) ? "" : webContentLink.replace("export=download", "export=view");
      var match = file[/* mimeType */6];
      switch (match) {
        case "application/pdf" : 
            return ReasonReact.element(/* None */0, /* None */0, Pdf$Drive.make(url, /* array */[]));
        case "image/jpeg" : 
            return ReasonReact.element(/* None */0, /* None */0, Image$Drive.make(url, file[/* name */1], /* array */[]));
        case "text/x-markdown" : 
            return ReasonReact.element(/* None */0, /* None */0, Markdown$Drive.make("Markdown content placeholder", /* array */[]));
        default:
          return Utils$Drive.stringElem("Preview");
      }
    });
  return newrecord;
}

export {
  component ,
  make ,
  
}
/*  Not a pure module */
