// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as RegisterServiceWorker from "./registerServiceWorker";
import * as EasyDrive$ReactTemplate from "./components/EasyDrive.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, EasyDrive$ReactTemplate.make(/* array */[])), "root");

RegisterServiceWorker.default();

export {
  
}
/*  Not a pure module */
