// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function stringElem(prim) {
  return prim;
}

function arrayElem(prim) {
  return prim;
}

export {
  stringElem ,
  arrayElem  ,
  
}
/* No side effect */
