// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE


function stringElem(prim) {
  return prim;
}

function arrayElem(prim) {
  return prim;
}

export {
  stringElem ,
  arrayElem ,
  
}
/* No side effect */
